---
all:
  children:
    f5:
      hosts:
        F5-01:
          ansible_host: 10.10.10.10
        F5-02:
          ansible_host: 10.10.10.9

    webservers:
      hosts:
        web01:
          ansible_host: 10.10.10.15
          application_ip: 10.10.11.16
          application_port: 80

        web02:
            ansible_host: 10.10.10.16
            application_ip: 10.10.11.17
            application_port: 80

        web03:
            ansible_host: 10.10.10.17
            application_ip: 10.10.11.18
            application_port: 80

      vars:
        ansible_user: greg
        ansible_ssh_private_key_file: /home/greg/.ssh/id_ed25519_f5lab
        ansible_become_method: sudo
        ansible_become_exe: /usr/bin/sudo.ws
